services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./../certs:/etc/nginx/ssl/certs
    restart: always
    network_mode: host
