services:
  minio:
    image: docker.arvancloud.ir/bitnami/minio:2024.11.7
    container_name: my-minio
    ports:
      - '9900:9000'
      - '9901:9001'
    networks:
      - minionetwork
    volumes:
      - './minio_data:/bitnami/minio/data'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
networks:
  minionetwork:
    driver: bridge
